twig:
    default_path: '%kernel.project_dir%/templates'
    globals:
        company_name: SecurePasswordGenerator
        company_name_short: SPG

when@test:
    twig:
        strict_variables: true
